update termux-url-opener

diff --git a/Android/termux-url-opener b/Android/termux-url-opener
--- a/Android/termux-url-opener
+++ b/Android/termux-url-opener
@@ -50,32 +50,18 @@ if [[ $installed == no ]];then
     echo -e "\e[091minstall failed!"
     exit $?
 fi
-echo -en "$formats\n
-    please give your input -: "
-read opt
+
 if [[ ! -d /sdcard/YoutubeVideos ]];then
     mkdir /sdcard/YoutubeVideos
 fi
+
 if [[ ! -d /sdcard/YoutubeAudio ]];then
     mkdir /sdcard/YoutubeAudio
 fi
-case $opt in 
-    a* | b* | c* | v* | e*)
-    cd /sdcard/YoutubeVideos
-    dlc=/sdcard/YoutubeVideos
-    ;;
-    d*)
-    cd /sdcard/YoutubeAudio
-    dlc=/sdcard/YoutubeAudio
-    ;;
-    s*)
-    echo "streaming..."
-    ;;
-    *)
-    echo -en "please give the right input -: "
-    read opt
-    case $opt in 
-        a* | b* | c* | v*| e*)
+
+check_input(){
+    case $@ in
+        a* | b* | c* | v* | e*)
         cd /sdcard/YoutubeVideos
         dlc=/sdcard/YoutubeVideos
         ;;
@@ -83,16 +69,33 @@ case $opt in
         cd /sdcard/YoutubeAudio
         dlc=/sdcard/YoutubeAudio
         ;;
-        -s*)
+        s*)
         echo "streaming..."
         ;;
         *)
-        echo -en "you did not give the right input, quitting..."
-        exit $?
+        echo -en "pleeaase give the right input -: "
+        read opt
+        case $opt in
+            a* | b* | c* | v*| e*)
+            cd /sdcard/YoutubeVideos
+            dlc=/sdcard/YoutubeVideos
+            ;;
+            d*)
+            cd /sdcard/YoutubeAudio
+            dlc=/sdcard/YoutubeAudio
+            ;;
+            s*)
+            echo "streaming..."
+            ;;
+            *)
+            echo -e "you did not give the right input, quitting...\n"
+            sleep .5
+            exit $?
+            ;;
+        esac
         ;;
     esac
-    ;;
-esac
+}
 
 # start of main code
 fnd() {
@@ -157,120 +160,134 @@ $(cat ${tmp_scrpt}|nl)\e[032m";sleep 1
 tmp_scrpt=~/cyt-`cat /dev/urandom | tr -cd 'a-z' | head -c 10|awk '{print $1}'`.sh
 LOG_FILE=~/.cyt-`cat /dev/urandom | tr -cd 'a-z' | head -c 4|awk '{print $1}'`
 HIST_FILE=~/.cyt-hist.tmp
-fnd_p() {
-  	echo $@ 
-    if [[ $1 == -l && $2 != s-l || $1 != s ]];then
-        shift 2;p=pl
-    elif [[ $2 == s* || $1 == s ]];then
-        if [[ $1 == -l ]];then
-            shift
-        fi
-        fnd "$@"
-        echo "$@">${HIST_FILE}
-        return
-    else
-        shift
-        p=p
-    fi
 
-    if [[ $(grep "+" <<< $(grep -oP '(?<=format\(s\):\s).*(?=)' ${LOG_FILE})) ]];then
-        formats=2
-    else
-        formats=1
-    fi
+if [ $1 == p ];then #play saved file if in history
+	if [ -f ${HIST_FILE} ];then
+		fnd `cat ${HIST_FILE}`
+	else
+		echo -e "\e[031m You haven't downloaded any file!"
+		exit 1
+	fi
+else
+	echo -en "$formats\n
+    	please give your input -: "
+	read opt
+	check_input $opt
+	fnd_p() {
 
-    if [[ $(grep downloaded ${LOG_FILE}) || $(grep "download]\s100%" ${LOG_FILE}|wc -l) == $formats \
-        || $(grep "download]\s100%" ${LOG_FILE}|wc -l) > $formats ]];then
-        LOG=`tac ${LOG_FILE}|grep -m1 -oP '(?<=]\s).*?(?=:\sDownloading)'`
-        if [[ ! -z $LOG ]];then 
-            check_command mpv
-            if [[ $installed == no ]];then
-                echo -e "\e[091minstall failed!"
-                exit $?
+        if [[ $1 == -l && $2 != s-l || $1 != s ]];then
+            shift 2;p=pl
+        elif [[ $2 == s* || $1 == s ]];then
+            if [[ $1 == -l ]];then
+                shift
             fi
-            fnd $p "$dlc" "$LOG"
-            echo "$p "$dlc" "$LOG"">${HIST_FILE}
+            fnd "$@"
+            echo "$@">${HIST_FILE}
+            return
         else
+            shift
+            p=p
+        fi
+
+        if [[ $(grep "+" <<< $(grep -oP '(?<=format\(s\):\s).*(?=)' ${LOG_FILE})) ]];then
+            formats=2
+        else
+            formats=1
+        fi
+
+        if [[ $(grep downloaded ${LOG_FILE}) || $(grep "download]\s100%" ${LOG_FILE}|wc -l) == $formats \
+            || $(grep "download]\s100%" ${LOG_FILE}|wc -l) > $formats ]];then
+            LOG=`tac ${LOG_FILE}|grep -m1 -oP '(?<=]\s).*?(?=:\sDownloading)'`
+            if [[ ! -z $LOG ]];then
+                check_command mpv
+                if [[ $installed == no ]];then
+                    echo -e "\e[091minstall failed!"
+                    exit $?
+                fi
+                fnd $p "$dlc" "$LOG"
+                echo "$p "$dlc" "$LOG"">${HIST_FILE}
+            else
+                return
+            fi
+
+        else
+            echo -e "Download failed!"
             return
         fi
-        
-    else
-        echo -e "Download failed!"
-        return
-    fi
-    rm ${LOG_FILE} >/dev/null 2>&1
+        rm ${LOG_FILE} >/dev/null 2>&1
 
-}
-aID="248+251"/"137+251"/"399+140"/"303+140"/"299+251"/"96"; bID="400+140"/"271+251" ; dID="140"/"251"/"250"
-cID="247+140"/"22+251"/"136+140"/"398+251" ; vID=b/"299+250"/"303+251"/"301"/"243+140"/"136+250"/hls-2176/http/mpeg/fallback
-eID="337+140"/"315+251"/"337+251"/"315+140"
-add_info="--embed-subs --sub-langs=en-orig,en --merge-output-format mp4"
-check_loop(){
-    if [[ $@ =~ -l ]];then
-        fnd_p -l $@
-    else
-        fnd_p $@
-    fi
-}
-# download and save to $dlc
-case $opt in
-    a)
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $aID $add_info "$1"
-    ;;
-    b)
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $bID $add_info "$1"
-    ;;
-    c)
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $cID $add_info "$1"
-    ;;
-    d)
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $dID --extract-audio --audio-format mp3 --audio-quality 1 "$1"
-    ;;
-    v)
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $vID $add_info "$1"
-    ;;
-    e)
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $eID $add_info "$1"
-    ;;
-    # download and play
-    dp|dp-l)
-    echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $dID --extract-audio --audio-format mp3 --audio-quality 1 "$1" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
-    check_loop $opt
-    ;;
-    ap-l|bp-l|cp-l|ep-l|vp-l)
-    echo "not playing videos!"
+    }
+    aID="248+251"/"137+251"/"399+140"/"303+140"/"299+251"/"96"; bID="400+140"/"271+251" ; dID="140"/"251"/"250"
+    cID="247+140"/"22+251"/"136+140"/"398+251" ; vID=b/"299+250"/"303+251"/"301"/"243+140"/"136+250"/hls-2176/http/mpeg/fallback
+    eID="337+140"/"315+251"/"337+251"/"315+140"
+    add_info="--embed-subs --sub-langs=en-orig,en --merge-output-format mp4"
+    check_loop(){
+        if [[ $@ =~ -l ]];then
+            fnd_p -l $@
+        else
+            fnd_p $@
+        fi
+    }
+    # download and save to $dlc
     case $opt in
-        ap-l|ap)
-        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $aID $add_info "$1" 
+        a)
+        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $aID $add_info "$1"
         ;;
-        bp-l|bp)
-        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $bID $add_info "$1" 
+        b)
+        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $bID $add_info "$1"
         ;;
-        cp-l|cp)
-        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $cID $add_info "$1" 
+        c)
+        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $cID $add_info "$1"
         ;;
-        vp-l|vp)
-        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $vID $add_info "$1" 
+        d)
+        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $dID --extract-audio --audio-format mp3 --audio-quality 1 "$1"
         ;;
-        ep-l|ep)
-        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $eID $add_info "$1" 
+        v)
+        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $vID $add_info "$1"
         ;;
-    esac
-    ;;
-    s*)
-    check_command mpv
-        if [[ $installed == no ]];then
-        echo -e "\e[091minstall failed!"
-        exit $?
-    fi
-    check_loop $opt -v --ytdl-format=b/$dID "$1"
-    
-    ;;
-    
-    *)
-    usage
-    exit $?
-    ;;
+        e)
+        echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $eID $add_info "$1"
+        ;;
+        # download and play
+        dp|dp-l)
+        echo -e "\e[032mSaving to $dlc\e[0m"
+        yt-dlp -f $dID --extract-audio --audio-format mp3 --audio-quality 1 "$1" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+        check_loop $opt
+        ;;
+        ap-l|bp-l|cp-l|ep-l|vp-l)
+        echo "not playing videos!"
+        case $opt in
+            ap-l|ap)
+            echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $aID $add_info "$1"
+            ;;
+            bp-l|bp)
+            echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $bID $add_info "$1"
+            ;;
+            cp-l|cp)
+            echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $cID $add_info "$1"
+            ;;
+            vp-l|vp)
+            echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $vID $add_info "$1"
+            ;;
+            ep-l|ep)
+            echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $eID $add_info "$1"
+            ;;
+        esac
+        ;;
+        s*)
+        check_command mpv
+            if [[ $installed == no ]];then
+            echo -e "\e[091minstall failed!"
+            exit $?
+        fi
+        check_loop $opt -v --ytdl-format=b/$dID "$1"
 
-esac
+        ;;
+
+        *)
+        usage
+        exit $?
+        ;;
+
+    esac
+fi
