update

diff --git a/GNU-linux/cyt-dl b/GNU-linux/cyt-dl
--- a/GNU-linux/cyt-dl
+++ b/GNU-linux/cyt-dl
@@ -26,7 +26,23 @@ if [[ $# -eq 0 || $1 == -help || $1 == --help || $1 == -h || $1 == --h ]] ; then
     exit 0
 fi
 
+check_command(){
+    if ! command -v $@ &>/dev/null ;then
+        echo -e "\e[091m$@ not found on system..quitting"
+    fi
+    return
+}
+check_command ffmpeg && check_command yt-dlp
+if [[ $(check_command ffmpeg) || $(check_command yt-dlp) ]];then
+    exit 1
+fi
+
+LOG_FILE=~/.cyt-list.sh
+
 #assign dlc to downloads folder
+if [[ ! -d ~/Downloads ]];then
+    mkdir ~/Downloads
+fi
 if [[ $# -eq 3 && -d $3 ]];then
     dlc="$(realpath "$3")"
     cd "$dlc"
@@ -48,11 +64,11 @@ fnd() {
             cd "$2"
             if [[ $(command -v mpv) && $(ps -ef|grep mpv|wc -l) < 2 ]];then
                 mpv_player() {
-                    echo "$(find -iname "*$3*" -exec echo \"{}\" \;)"|grep -v ".json">${tmp_scrpt}
+                    echo "$(find -iname "*$3*" -exec echo \"{}\" \;)"|grep -vE ".json|.part">${tmp_scrpt}
                     if [[ $(cat ${tmp_scrpt}) ]];then
                         echo -en "\e[033mPlaying:\e[094m"
                         list='';while IFS= read li;do list="$list $li";done <${tmp_scrpt}
-                        bash<<<$(echo "mpv -v --fs $list >/dev/null 2>&1 &")
+                        bash<<<$(echo "mpv --player-operation-mode=pseudo-gui -v $list >/dev/null 2>&1 &")
                         echo -e "
 $(cat ${tmp_scrpt}|nl)\e[032m";sleep 1
                         #remove temp files
@@ -64,12 +80,12 @@ $(cat ${tmp_scrpt}|nl)\e[032m";sleep 1
                 mpv_player "$@"
             elif [[ $(command -v vlc) ]];then
                 vlc_player() {
-                    echo "$(find -iname "*$3*" -exec echo "vlc -q --fullscreen --one-instance --playlist-enqueue --play-and-exit \"{}\" >/dev/null 2>&1 &" \;)"|grep -v ".json">${tmp_scrpt}
+                    echo "$(find -iname "*$3*" -exec echo "vlc -q --fullscreen --one-instance --playlist-enqueue --play-and-exit \"{}\" >/dev/null 2>&1 &" \;)"|grep -vE ".json|.part">${tmp_scrpt}
                     if [[ $(cat ${tmp_scrpt}) ]];then
                         echo -en "\e[033mAdding to playlist:\e[094m"
                         bash ${tmp_scrpt}
                         echo -e "
-$(find -iname "*$3*" -exec echo \'{}\' \;|grep -v ".json"|nl)\e[032m";sleep 1
+$(find -iname "*$3*" -exec echo \'{}\' \;|grep -vE ".json|.part"|nl)\e[032m";sleep 1
                         #remove temp files
                         rm ${tmp_scrpt} >/dev/null 2>&1
                     else
@@ -79,11 +95,11 @@ $(find -iname "*$3*" -exec echo \'{}\' \;|grep -v ".json"|nl)\e[032m";sleep 1
                 vlc_player "$@"
             else
                 mpv_player() {
-                    echo "$(find -iname "*$3*" -exec echo \"{}\" \;)"|grep -v ".json">${tmp_scrpt}
+                    echo "$(find -iname "*$3*" -exec echo \"{}\" \;)"|grep -vE ".json|.part">${tmp_scrpt}
                     if [[ $(cat ${tmp_scrpt}) ]];then
                         echo -en "\e[033mPlaying:\e[094m"
                         list='';while IFS= read li;do list="$list $li";done <${tmp_scrpt}
-                        bash<<<$(echo "mpv -v --fs $list >/dev/null 2>&1 &")
+                        bash<<<$(echo "mpv --player-operation-mode=pseudo-gui -v $list >/dev/null 2>&1 &")
                         echo -e "
 $(cat ${tmp_scrpt}|nl)\e[032m";sleep 1
                         #remove temp files
@@ -105,11 +121,11 @@ $(cat ${tmp_scrpt}|nl)\e[032m";sleep 1
             cd "$2"
             if [[ $(command -v mpv) && $(ps -ef|grep mpv|wc -l) < 2 ]];then
                 mpv_player() {
-                    find -iname "*$3*" -exec echo "\"{}\"" \;|grep -v ".json" >${tmp_scrpt}
+                    find -iname "*$3*" -exec echo "\"{}\"" \;|grep -vE ".json|.part" >${tmp_scrpt}
                     if [[ $(cat ${tmp_scrpt}) ]];then
                         echo -en "\e[033mPlaying:\e[094m"
                         list="";while IFS= read -r li;do list="$list $li";done<${tmp_scrpt}
-                        bash<<<$(echo "mpv -v --loop-file=3 --fs$list >/dev/null 2>&1 &"|grep -v ".json")
+                        bash<<<$(echo "mpv -v --loop-file=3 --player-operation-mode=pseudo-gui $list >/dev/null 2>&1 &"|grep -vE ".json|.part")
                         echo -e "
 $(cat ${tmp_scrpt}|nl)\e[032m";sleep 1
                         #remove temp files
@@ -121,12 +137,12 @@ $(cat ${tmp_scrpt}|nl)\e[032m";sleep 1
                 mpv_player "$@"
             elif [[ $(command -v vlc) ]];then
                 vlc_player() {
-                    echo "$(find -iname "*$3*" -exec echo "vlc -q --fullscreen --one-instance --playlist-enqueue --play-and-exit \"{}\" >/dev/null 2>&1 &" \;)"|grep -v ".json">${tmp_scrpt}
+                    echo "$(find -iname "*$3*" -exec echo "vlc -q --fullscreen --one-instance --playlist-enqueue --play-and-exit \"{}\" >/dev/null 2>&1 &" \;)"|grep -vE ".json|.part">${tmp_scrpt}
                     if [[ $(cat ${tmp_scrpt}) ]];then
                         echo -en "\e[033mAdding to playlist:\e[094m"
                         bash<<<$(for i in {1..4};do echo "`cat ${tmp_scrpt}`";done) 
                         echo -e "
-$(find -iname "*$3*" -exec echo \'{}\' \;|grep -v ".json"|nl)\e[032m";sleep 1
+$(find -iname "*$3*" -exec echo \'{}\' \;|grep -vE ".json|.part"|nl)\e[032m";sleep 1
                         #remove temp files
                         rm ${tmp_scrpt} >/dev/null 2>&1
                     else
@@ -136,11 +152,11 @@ $(find -iname "*$3*" -exec echo \'{}\' \;|grep -v ".json"|nl)\e[032m";sleep 1
                 vlc_player "$@"  
             else
                 mpv_player() {
-                    find -iname "*$3*" -exec echo "\"{}\"" \;|grep -v ".json" >${tmp_scrpt}
+                    find -iname "*$3*" -exec echo "\"{}\"" \;|grep -vE ".json|.part" >${tmp_scrpt}
                     if [[ $(cat ${tmp_scrpt}) ]];then
                         echo -en "\e[033mPlaying:\e[094m"
                         list="";while IFS= read -r li;do list="$list $li";done<${tmp_scrpt}
-                        bash<<<$(echo "mpv -v --loop-file=3 --fs$list >/dev/null 2>&1 &"|grep -v ".json")
+                        bash<<<$(echo "mpv -v --loop-file=3 --player-operation-mode=pseudo-gui $list >/dev/null 2>&1 &"|grep -vE ".json|.part")
                         echo -e "
 $(cat ${tmp_scrpt}|nl)\e[032m";sleep 1
                         #remove temp files
@@ -163,14 +179,14 @@ $(cat ${tmp_scrpt}|nl)\e[032m";sleep 1
 	esac
 
 }
-tmp_scrpt=/tmp/cyt-fnd.sh
-LOG_FILE=/tmp/.cyt-tmp
+tmp_scrpt=/tmp/cyt-`cat /dev/urandom | tr -cd 'a-z' | head -c 10|awk '{print $1}'`.sh
+LOG_FILE=/tmp/.cyt-`cat /dev/urandom | tr -cd 'a-z' | head -c 4|awk '{print $1}'`
 HIST_FILE=~/.cyt-hist.tmp
 fnd_p() {
    
     if [[ $1 == -l ]];then
         shift;p=pl
-    elif [[ $1 == -s ]];then
+    elif [[ $1 == -s* ]];then
         shift
         echo "s $@">${HIST_FILE}
         fnd `cat ${HIST_FILE}` 
@@ -195,7 +211,7 @@ fnd_p() {
                 echo -e "\e[031mYou need to download mpv to play file!\e[0m"
                 exit $?
             fi
-            echo "$p \"$dlc\" "$LOG"">${HIST_FILE}
+            echo "$p "$dlc" "$LOG"">${HIST_FILE}
         else
             return
         fi
@@ -207,52 +223,66 @@ fnd_p() {
     rm ${LOG_FILE} >/dev/null 2>&1
 
 }
+#check requirements
+check_command(){
+	if [[ ! $(command -v $@) ]];then
+        echo -en "\e[091mcommand $@ not found! "
+        return
+    fi
+}
+check_command yt-dlp && check_command ffmpeg
+
+if [[ $(check_command yt-dlp) || $(check_command ffmpeg) ]];then
+    echo "Quiting.."
+    exit 1
+fi
 aID="248+251"/"137+251"/"399+140"/"303+140"/"299+251"/"96"; bID="400+140"/"271+251" ; dID="140"/"251"/"250"
 cID="247+140"/"22+251"/"136+140"/"398+251" ; vID=b/"299+250"/"303+251"/"301"/"243+140"/"136+250"/hls-2176/http/mpeg/fallback
 eID="337+140"/"315+251"/"337+251"/"315+140"
+add_info="--embed-subs --sub-langs=en-orig,en"
 
 #default storage as windows downloads folder
 if [[ $# -eq 2 && -d $dlc && $1 == a ]]; then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $aID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $aID --merge-output-format mp4 $add_info "$2"
 elif [[ $# -eq 2 && -d $dlc && $1 == b ]]; then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $bID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $bID --merge-output-format mp4 $add_info "$2"
 elif [[ $# -eq 2 && -d $dlc && $1 == c ]]; then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $cID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $cID --merge-output-format mp4 $add_info "$2"
 elif [[ $# -eq 2 && -d $dlc && $1 == d ]]; then
     echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $dID --extract-audio --audio-format mp3 --audio-quality 1 "$2"
 elif [[ $# -eq 2 && -d $dlc && $1 == v ]];then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $vID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $vID --merge-output-format mp4 $add_info "$2"
 elif [[ $# -eq 2 && -d $dlc && $1 == e ]];then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $eID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $eID --merge-output-format mp4 $add_info "$2"
 
 #for known folders do,
 elif [[ $# -eq 3 && -d $dlc && $1 == a ]]; then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $aID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $aID --merge-output-format mp4 $add_info "$2"
 elif [[ $# -eq 3 && -d $dlc && $1 == b ]]; then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $bID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $bID --merge-output-format mp4 $add_info "$2"
 elif [[ $# -eq 3 && -d $dlc && $1 == c ]]; then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $cID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $cID --merge-output-format mp4 $add_info "$2"
 elif [[ $# -eq 3 && -d $dlc && $1 == d ]]; then
     echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $dID --extract-audio --audio-format mp3 --audio-quality 1 "$2"
 elif [[ $# -eq 3 && -d $dlc && $1 == v ]];then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $vID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $vID --merge-output-format mp4 $add_info "$2"
 elif [[ $# -eq 3 && -d $dlc && $1 == e ]];then
-    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $eID --merge-output-format mp4 --embed-subs "$2"
+    echo -e "\e[032mSaving to $dlc\e[0m";yt-dlp -f $eID --merge-output-format mp4 $add_info "$2"
 
 #default storage as windows downloads folder
 elif [[ $# -eq 2 && -d $dlc && $1 == ap ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $aID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $aID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 
 elif [[ $# -eq 2 && -d $dlc && $1 == bp ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $bID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $bID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 
 elif [[ $# -eq 2 && -d $dlc && $1 == cp ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $cID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $cID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 
 elif [[ $# -eq 2 && -d $dlc && $1 == dp ]];then
@@ -262,27 +292,27 @@ elif [[ $# -eq 2 && -d $dlc && $1 == dp ]];then
 
 elif [[ $# -eq 2 && -d $dlc && $1 == vp ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $vID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $vID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 elif [[ $# -eq 2 && -d $dlc && $1 == ep ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $eID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $eID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 
 #default storage as windows downloads folder and if loop enabled, do
 elif [[ $# -eq 3 && -d $dlc && $1 == ap && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $aID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $aID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 
 elif [[ $# -eq 3 && -d $dlc && $1 == bp && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $bID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $bID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 
 elif [[ $# -eq 3 && -d $dlc && $1 == cp && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $cID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $cID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 
 elif [[ $# -eq 3 && -d $dlc && $1 == dp && $2 == -l ]];then
@@ -292,27 +322,27 @@ elif [[ $# -eq 3 && -d $dlc && $1 == dp && $2 == -l ]];then
 
 elif [[ $# -eq 3 && -d $dlc && $1 == vp && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $vID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $vID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 elif [[ $# -eq 3 && -d $dlc && $1 == ep && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $eID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $eID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 
 #for known downloads directory, do
 elif [[ $# -eq 3 && -d $3 && $1 == ap ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $aID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $aID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 
 elif [[ $# -eq 3 && -d $3 && $1 == bp ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $bID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $bID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 
 elif [[ $# -eq 3 && -d $3 && $1 == cp ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $cID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $cID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 
 elif [[ $# -eq 3 && -d $3 && $1 == dp ]];then
@@ -322,27 +352,27 @@ elif [[ $# -eq 3 && -d $3 && $1 == dp ]];then
 
 elif [[ $# -eq 3 && -d $3 && $1 == vp ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $vID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $vID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 elif [[ $# -eq 3 && -d $3 && $1 == ep ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $eID --merge-output-format mp4 --embed-subs "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $eID --merge-output-format mp4 $add_info "$2" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p
 
 #for known downloads directory and if loop enabled, do
 elif [[ $# -eq 4 && -d $4 && $1 == ap && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $aID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $aID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 
 elif [[ $# -eq 4 && -d $4 && $1 == bp && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $bID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $bID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 
 elif [[ $# -eq 4 && -d $4 && $1 == cp && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $cID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $cID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 
 elif [[ $# -eq 4 && -d $4 && $1 == dp && $2 == -l ]];then
@@ -352,11 +382,11 @@ elif [[ $# -eq 4 && -d $4 && $1 == dp && $2 == -l ]];then
 
 elif [[ $# -eq 4 && -d $4 && $1 == vp && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $vID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $vID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 elif [[ $# -eq 4 && -d $4 && $1 == ep && $2 == -l ]];then
     echo -e "\e[032mSaving to $dlc\e[0m"
-    yt-dlp -f $eID --merge-output-format mp4 --embed-subs "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
+    yt-dlp -f $eID --merge-output-format mp4 $add_info "$3" > >(tee ${LOG_FILE}) 2> >(tee ${LOG_FILE} 2>&1)
     fnd_p -l
 
 #play later
@@ -381,6 +411,7 @@ elif [[ $1 == -s* ]];then #stream
             \e[035mb\e[0m: 1440p Video
             \e[035mc\e[0m: 720p Video
             \e[035md\e[0m: mp3 Audio
+            \e[035me\e[0m: Downloads 2160p Video
             \e[035mv\e[0m: if all of the above formats fail or non-youtube videos\n"
                 echo -en "select format\n$formats \n -: "
                 read opt
@@ -394,12 +425,12 @@ elif [[ $1 == -s* ]];then #stream
         cd ~/Downloads 
         if [[ $# -eq 2 ]];then
             format_selector $1
-            fnd_p -s -v --player-operation-mode=pseudo-gui --ytdl-format=$opt --ytdl-raw-options="no-simulate=,skip-download=,write-auto-sub=,sub-langs=en=,output=./%(title)s-%(id)s.%(ext)s"= --fs "$2"
+            fnd_p -s -v --player-operation-mode=pseudo-gui --ytdl-format=$opt --fs "$2"
         elif [[ $# -eq 3 && $2 == -l ]];then
             format_selector $1
             shift
             for times in {1..4};do
-                fnd_p -s -v --player-operation-mode=pseudo-gui --ytdl-format=$opt --ytdl-raw-options="no-simulate=,skip-download=,write-auto-sub=,sub-langs=en=,output=./%(title)s-%(id)s.%(ext)s"= --fs "$2">&2
+                fnd_p -s -v --player-operation-mode=pseudo-gui --ytdl-format=$opt --fs "$2">&2
             done
         elif [[ $# > 3 && $2 == -l ]];then
             echo -e "\e[031mloop option is available for one file only!\e[0m"
